# 数据库连接配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  application:
    name: main-service 

  mvc:
    static-path-pattern: /Data/**
  
  web:
    resources:
      static-locations: classpath:/static,classpath:/public,classpath:/resources,classpath:/META-INF/resources,file:D:/projects/onlinebookstore/demo/Data/s

  data:
    redis:
      host: localhost         # Redis服务器主机
      port: 6379              # Redis端口号，默认6379
      password:               # Redis密码（如果有的话）
      database: 0             # Redis数据库索引（默认为0）
      timeout: 300ms          # 连接超时时间

    mongodb:
      host: localhost
      port: 27017
      database: onlinebookstore
      auto-index-creation: true
      
    neo4j:
      uri: bolt://localhost:7687
      username: neo4j
      password: luoyiyu599

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/